### ISSUE TITLE
[HTML, CSS] Create Desert recipes page

### ISSUE THREAD

**Issue by AjShatalii** [GSG-CF05/Foodster-Team04#8]
### Page contents 

- Page title
- A search box for the user to enter the name of the recipe they're looking for 
- Small boxes that contain random recipes in the dessert section
- A picture of each dessert with its name underneath it

### UI
![X - 7](https://user-images.githubusercontent.com/26528525/159037785-b27a2e64-8d33-4694-bfb6-715558bbf398.png)

**Comment by shathakh** [comment]
takes 20min
