### ISSUE TITLE
[HTML, CSS] Create the search page for a chosen category 

### ISSUE THREAD

**Issue by AjShatalii** [GSG-CF05/Foodster-Team04#9]
### Page contents

- The page title will be according to whatever category the user will choose. For example, Beef recipes 
- A search box for the user to enter the name of the recipe they're looking for
- Small boxes that contain random recipes in a given category
- A picture of each recipe with its name underneath it 

### UI
![X - 5](https://user-images.githubusercontent.com/26528525/159039557-bbf84caa-d02d-416a-aab7-100d09781560.png)

**Comment by shathakh** [comment]
takes 20min
